name: sqltree
description: A library for building sql queries through a tree representation.
version: 0.0.1
author: Roberto Tassi <roberto.tassi@fromlabs.org>
homepage: https://github.com/fromlabs/sqltree

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  collection: "^1.8.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
